### PR TITLE
Misc improvements

### PR DESCRIPTION
**Pull request by miguelsousa**

### CODE REVIEW

**Comment by miguelsousa** [comment]
@brew please leave it open. I have a few more changes in the works.

**Comment by brew** [comment]
@miguelsousa Looks great, ping me in this thread when this is ready to merge.

**Comment by miguelsousa** [comment]
@brew I'm done. There's a few more things that I'd like to improve but I'll leave them for later. I'll open a few issues to keep track of them.

**Comment by brew** [comment]
Marvellous, thanks @miguelsousa!

**Comment by brew** [comment]
@kennethormandy you may want to pull these changes into the Atom package.

**Pull request merged**
